spring:
  profiles:
    active:
    - dog
    - EN
    - prod

matteo:
  username: YmlUserName
  password: YmlPwd
  jdbcUrl: YmlUrl


---
spring:
  profiles: prod
matteo:
  username: ProdYmlUserName
  password: ProdYmlPws
  jdbcUrl: ProdYmlUrl